### ISSUE TITLE
インデントについて

### ISSUE THREAD

**Issue by geckotang** [webcre8/html5style#27]
@hatch2 @oti @webcre8 #26 で出た話です。

現状は、この[ルール](https://github.com/webcre8/html5style/blob/gh-pages/.editorconfig)

でやっているのですが、基本的にソフトタブ（半角スペース）によるインデントに移行しようと思います。（この.editorconfigは、僕が書いたやつです...）

| 言語 | インデント方法 |
| --- | --- |
| 全般 | 半角スペース2 |
| HTML | 半角スペース2 |
| CSS/SCSS | 半角スペース2 |
| JS | 半角スペース4 |

がいいかなと思うんですが、どうでしょうか。
以降するときは、gh-pagesにマージされてる奴だけ@geckotangが置換して、PRs中の奴はpushした人になおしていただく感じがよいかなと思います...
### 表示サンプル

``` html
<!-- space:2 -->
<div>
  <div>1</div>
  <div>2</div>
</div>
<!-- space:4 -->
<div>
    <div>1</div>
    <div>2</div>
</div>
```

``` css
/* space:2 */
.div {
  display: block;
}
/* space:4 */
.div {
    display: block;
}
```

``` scss
/* space:2 */
.div {
  display: block;
  div {
    display: block;
  }
}
/* space:4 */
.div {
    display: block;
    div {
        display: block;
    }
}
```

``` js
//space:4
var hoge = '',
    foo = '';
//space:2
var hoge = '',
  foo = '';
```
